DROP TABLESPACE TSHANACON_D INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE TSHANACON_D DATAFILE 
  'D:\Oracle\oradata\HANADATA\HANACON_DATA01.DBF' SIZE 1024M AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE TSHANACON_I INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE TSHANACON_I DATAFILE 
  'D:\Oracle\oradata\HANADATA\HANACON_INDEX01.DBF' SIZE 512M AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

