 -- 사건 데이터 초기화
 
 DELETE FROM TB_AC_AFFAIRPRSNOTE_LST
 where AFF_SEQ < 10490;
 
 DELETE FROM TB_AC_AFFAIRPRS_LST
  where AFF_SEQ < 10490;
 
 DELETE FROM TB_AC_AFFAIROUT_LST
  where AFF_SEQ < 10490;
  
 DELETE FROM TB_AC_AFFAIR_DTL
  where AFF_SEQ < 10490;
  
 DELETE FROM TB_AC_AFFNOTE_LST
  where AFF_SEQ < 10490;
 
 DELETE FROM TB_AC_COC_LST
  where AFF_SEQ < 10490;
 
 DELETE FROM TB_AC_FAX_LST
  where AFF_SEQ < 10490;

 DELETE FROM TB_AC_TIEUPASK_DTL
  where AFF_SEQ < 10490;

 
 DELETE FROM TB_AC_AFFAIR_MST
  where AFF_SEQ < 10490;
 
 