

-- 기존 사건을 새로운 사건으로 복사하기
DECLARE 
    V_AFF_SEQ NUMBER(10);
    OLD_AFF_SEQ NUMBER(10);    
BEGIN
    OLD_AFF_SEQ := 2000909;
    BEGIN
        SELECT SQ_AC_AFFAIR_LST.NEXTVAL
          INTO V_AFF_SEQ
          FROM DUAL;
    END;
    BEGIN     
        INSERT INTO TB_AC_AFFAIR_MST
        (BRCH_ID, AFF_SEQ, TUB_SEQ, CHG_SEQ, TUB_NM, CHG_NM, TUB_TEL, TUB_FAX, HNA_CHG_USR, HNA_CHG_USR_NM, PRS_CHG_USR, DOC_CRT_USR, AFF_ST_DT, AFF_ED_DT, AFF_NO, AFF_GBN, CLT_NM, CLT_TEL, CLT_JMN, CLT_ADDR, CLT_ZIP, DOC_CARY, AFF_PRS_STS, CRT_USR, CRT_DT, EDT_USR, EDT_DT, CHG_PRS_NOTE, AFF_ETC_ED_DT, SMT_PLC, ADD_INF_GBN, BEF_CLT_NM, BEF_CLT_JMN, ASK_EXP_DT, TUB_PAY_SEQ, GPAY_YN, SIN_NM)
        SELECT BRCH_ID,  V_AFF_SEQ, TUB_SEQ, CHG_SEQ, TUB_NM, CHG_NM, TUB_TEL, TUB_FAX, HNA_CHG_USR, HNA_CHG_USR_NM, PRS_CHG_USR, DOC_CRT_USR, AFF_ST_DT, AFF_ED_DT, AFF_NO, AFF_GBN, CLT_NM || '(복사)', CLT_TEL, CLT_JMN, CLT_ADDR, CLT_ZIP, DOC_CARY, AFF_PRS_STS, CRT_USR, CRT_DT, EDT_USR, EDT_DT, CHG_PRS_NOTE, AFF_ETC_ED_DT, SMT_PLC, ADD_INF_GBN, BEF_CLT_NM, BEF_CLT_JMN, ASK_EXP_DT, TUB_PAY_SEQ, GPAY_YN, SIN_NM
          FROM TB_AC_AFFAIR_MST
         WHERE AFF_SEQ = OLD_AFF_SEQ;
        INSERT INTO TB_AC_AFFAIR_DTL
        (BRCH_ID, AFF_SEQ, DTL_SEQ, GRP_CD, GRP_SEQ, REQ_SEQ, SORT_NO, REQ_BND_SEQ, REQ_BND_NM, REQ_BND_STS, REQ_DEB, REQ_BNK, REQ_CARD, BNK_NOTE, CARD_NOTE, BIZ_REQ_YN, REQ_PRT_YN, BND_SEQ_1, BND_NM_1, PRS_STS_1, BND_SEQ_2, BND_NM_2, PRS_STS_2, ISU_DEB, ISU_COC, ISU_BNK, ISU_CARD, ISU_CRDT, BNK_CHRG, AGC_CHRG, PRT_YN, CLOSE_YN, CRT_USR, CRT_DT, EDT_USR, EDT_DT, NOTE, PRS_NOTE_1, PRS_NOTE_2, ACP_MTD_1, ACP_MTD_2, NOTE2, REQ_PRS_NOTE, BNK_NOTE_TRM, BNK_NOTE_ETC, CARD_NOTE_TRM, CARD_NOTE_ETC)
        SELECT BRCH_ID, V_AFF_SEQ, DTL_SEQ, GRP_CD, GRP_SEQ, REQ_SEQ, SORT_NO, REQ_BND_SEQ, REQ_BND_NM, REQ_BND_STS, REQ_DEB, REQ_BNK, REQ_CARD, BNK_NOTE, CARD_NOTE, BIZ_REQ_YN, REQ_PRT_YN, BND_SEQ_1, BND_NM_1, PRS_STS_1, BND_SEQ_2, BND_NM_2, PRS_STS_2, ISU_DEB, ISU_COC, ISU_BNK, ISU_CARD, ISU_CRDT, BNK_CHRG, AGC_CHRG, PRT_YN, CLOSE_YN, CRT_USR, CRT_DT, EDT_USR, EDT_DT, NOTE, PRS_NOTE_1, PRS_NOTE_2, ACP_MTD_1, ACP_MTD_2, NOTE2, REQ_PRS_NOTE, BNK_NOTE_TRM, BNK_NOTE_ETC, CARD_NOTE_TRM, CARD_NOTE_ETC
          FROM TB_AC_AFFAIR_DTL
         WHERE AFF_SEQ = OLD_AFF_SEQ; 
    END;
END; 
 
 