-- 기존꺼로 백업

create TABLE TB_CC_TIEUP_LST_IMP
AS 
SELECT *
  FROM TB_CC_TIEUP_LST

create TABLE TB_CC_TIEUPCHG_LST_IMP
AS 
SELECT *
  FROM TB_CC_TIEUPCHG_LST

create TABLE TB_CC_TIEUPNOTE_LST_IMP
AS 
SELECT *
  FROM TB_CC_TIEUPNOTE_LST




-- 데이터 초기화(장표 테스트용 제휴사 제외)

DELETE FROM TB_CC_TIEUPCHG_LST
WHERE TUB_SEQ != 10000

DELETE FROM TB_CC_TIEUPNOTE_LST
WHERE TUB_SEQ != 10000

DELETE FROM TB_CC_TIEUP_LST
  WHERE TUB_SEQ != 10000

-- 데이터 초기화(장표 테스트용 채권사는 제외)



-- MS-SQL SERVER MANAGMENT STUDIO 로 데이터 이관


SELECT DISTINCT 우편번호
  FROM 채권사정보



INSERT INTO TB_CC_BOND_LST
(BRCH_ID,
BND_SEQ,
BND_NM,
BND_TEL,
BND_FAX,
BND_ADDR,
BND_ZIP,
ZONE_GBN,
DT_GBN,
ACC_NO,
CHRG_AMT,
BIZ_PRT_YN,
FORM_FILE,
ISU_EXP_DD,
RLT_NM,
BUY_BND,
SEL_ROUT,
ISU_TIP,
CRT_USR,
CRT_DT,
EDT_USR,
EDT_DT,
FORM_SAVE_FILE,
ACP_MTD,
FORM_GBN,
ISU_NOTE,
REG_GBN,
STP_OUT_GBN,
OLD_BND_SEQ,
BND_FUL_NM,
OLD_ACP_MTD,
OLD_FORM_GBN,
OLD_BONDSPOT_NM)
SELECT 'H10' AS BRCH_ID,
       20000 + ROWNUM AS BND_SEQ, 
       NVL(채권사명칭,채권사) AS BND_NM,
       전화번호 BND_TEL,
       팩스번호 BND_FAX,
       주소 BND_ADDR,
       SUBSTR(우편번호,1,7) BND_ZIP,
       CASE 
            WHEN 구분 = '1구역' THEN '1'
            WHEN 구분 = '2구역' THEN '2'
            ELSE NULL 
       END ZONE_GBN,
       NULL DT_GBN,
       계좌번호 ACC_NO,
       수수료 CHRG_AMT,
       DECODE(사업자등록증,'필요', 'Y', 'N') BIZ_PRT_YN,        
       NULL FORM_FILE,
       발급예상기간 ISU_EXP_DD,
       관련명칭 RLT_NM,
       매입채권 BUY_BND,
       매각경로 SEL_ROUT,
       "발급Tip" ISU_TIP,
       'SYSTEM' CRT_USR,
        SYSDATE CRT_DT,
        'SYSTEM' EDT_USR,
        SYSDATE EDT_DT,        
       NULL FORM_SAVE_FILE,
       CASE 
            WHEN TRIM(접수방법) IN ('등기') THEN 'D'
            WHEN TRIM(접수방법) IN ('팩스', '팩스진행','fax') THEN 'D'
            WHEN TRIM(접수방법) IN ('원격', '원격지') THEN 'R'
            WHEN TRIM(접수방법) IN ('방문', '방문(지점별)') THEN 'I'
             WHEN TRIM(접수방법) IN ('등기+반송') THEN 'DR'
            ELSE NULL 
       END ACP_MTD,
       CASE 
            WHEN TRIM(서류) LIKE '%자체양식%' THEN 'S'
            WHEN TRIM(서류) LIKE '%기본%' THEN 'C'
            ELSE 'N' 
       END FORM_GBN,
       NULL ISU_NOTE,
       'A' REG_GBN,
       DECODE(도장반출,'반출','Y','N') STP_OUT_GBN,
       채권사코드 OLD_BND_SEQ,
       채권사 BND_FUL_NM,
        접수방법 OLD_ACP_MTD,
        서류 OLD_FORM_GBN,
        지점정보
  FROM (select *
          from 채권사정보
        order by  채권사코드 
       ) A





SELECT TO_CHAR(지점정보)
  FROM 채권사정보
 WHERE 지점정보 IS NOT NULL



COMMIT




SELECT * FROM TB_CC_USERBOND_LST
WHERE BND_SEQ != 10000

SELECT * FROM TB_CC_BONDSPOT_LST
WHERE BND_SEQ = 10000

SELECT * FROM TB_CC_BOND_LST
WHERE BND_SEQ = 10000









INSERT INTO TB_CC_BOND_LST
(BRCH_ID, BND_SEQ, BND_NM, BND_TEL, BND_FAX, BND_ADDR, BND_ZIP, ZONE_GBN, DT_GBN, ACC_NO, CHRG_AMT, BIZ_PRT_YN, FORM_FILE, ISU_EXP_DD, RLT_NM, BUY_BND, SEL_ROUT, ISU_TIP, CRT_USR, CRT_DT, EDT_USR, EDT_DT, FORM_SAVE_FILE, ACP_MTD, FORM_GBN, ISU_NOTE, REG_GBN)
select BRCH_ID, BND_SEQ, BND_NM, BND_TEL, BND_FAX, BND_ADDR, BND_ZIP, ZONE_GBN, DT_GBN, ACC_NO, CHRG_AMT, BIZ_PRT_YN, FORM_FILE, ISU_EXP_DD, RLT_NM, BUY_BND, SEL_ROUT, ISU_TIP, CRT_USR, CRT_DT, EDT_USR, EDT_DT, FORM_SAVE_FILE, ACP_MTD, FORM_GBN, ISU_NOTE, REG_GBN
  from tb_cc_bond_lst_TEMP
 WHERE BND_SEQ = 10000 
 
 
 
INSERT INTO TB_CC_TIEUP_LST 
(BRCH_ID, TUB_SEQ, TUB_NM, TUB_TEL, TUB_FAX, TUB_ADDR, TUB_ZIP, BAG_AGC_AMT, ETC_AGC_AMT, SIN_NM, SIN_TEL, SIN_GBN, SIN_5, SIN_10, SIN_15, SIN_20, SIN_25, SIN_99, RCP_GBN, BIL_GBN, DEAL_STS, DEAL_STOP_RSN, HNA_CHG_USR, DOC_CARY, BIZ_FILE_NM, CRT_USR, CRT_DT, EDT_USR, EDT_DT, BIZ_FILE_SAVE_NM, AFF_REG_NOTE, AFF_PRS_NOTE, COST_NOTE, REG_GBN, RLT_NM)
SELECT BRCH_ID, TUB_SEQ, TUB_NM, TUB_TEL, TUB_FAX, TUB_ADDR, TUB_ZIP, BAG_AGC_AMT, ETC_AGC_AMT, SIN_NM, SIN_TEL, SIN_GBN, SIN_5, SIN_10, SIN_15, SIN_20, SIN_25, SIN_99, RCP_GBN, BIL_GBN, DEAL_STS, DEAL_STOP_RSN, HNA_CHG_USR, DOC_CARY, BIZ_FILE_NM, CRT_USR, CRT_DT, EDT_USR, EDT_DT, BIZ_FILE_SAVE_NM, AFF_REG_NOTE, AFF_PRS_NOTE, COST_NOTE, REG_GBN, RLT_NM
  FROM TB_Cc_TIEUP_LST_TEMP 
WHERE TUB_SEQ = 10000 
 
 order by bnd_seq
 
 
INSERT INTO  



TB_AC_AFFAIR_MST