-- 기존꺼로 백업

create TABLE TB_CC_TIEUP_LST_TEMP
AS 
SELECT *
  FROM TB_CC_TIEUP_LST

create TABLE TB_CC_TIEUPCHG_LST_TEMP 
AS 
SELECT *
  FROM TB_CC_TIEUPCHG_LST

  
SELECT *
  FROM TB_CC_BOND_LST


-- 데이터 초기화

DELETE FROM TB_CC_TIEUPCHG_LST

DELETE FROM TB_CC_TIEUPNOTE_LST


DELETE FROM TB_CC_TIEUP_LST


COMMIT


-- 엑셀 데이터 넣기

DELETE FROM ERP_TEMP_TABLE 

-- INSERT~~~


-- 제휴사명과 담당을 분리
-- 한 엑셀에 제휴사 담당자 다 ~ 있다. 제휴사 결재자 => 담당자로 

SELECT COUNT(*)
  FROM ERP_TEMP_TABLE

SELECT ATTR01, ATTR02, ATTR03, ATTR04, ATTR05, ATTR06, ATTR07, ATTR10, ATTR11, ATTR12, ATTR13, ATTR14, ATTR15, ATTR16, ATTR17, ATTR18, ATTR19, ATTR20, ATTR21, ATTR22, ATTR23, ATTR24, COUNT(*)
  FROM ERP_TEMP_TABLE
 GROUP BY ATTR01, ATTR02, ATTR03, ATTR04, ATTR05, ATTR06, ATTR07, ATTR10, ATTR11, ATTR12, ATTR13, ATTR14, ATTR15, ATTR16, ATTR17, ATTR18, ATTR19, ATTR20, ATTR21, ATTR22, ATTR23, ATTR24  

-- 중복되는데 값이 요상하므로 제휴사중 ID 가 제일 낮은거로 넣기 
-- 제휴사 넣기 
INSERT INTO TB_CC_TIEUP_LST
(BRCH_ID, TUB_SEQ, TUB_NM, TUB_TEL, TUB_FAX, TUB_ADDR, TUB_ZIP, BAG_AGC_AMT, ETC_AGC_AMT, SIN_NM, SIN_TEL, SIN_GBN, SIN_5, SIN_10, SIN_15, SIN_20, SIN_25, SIN_99, RCP_GBN, BIL_GBN, DEAL_STS, DEAL_STOP_RSN, HNA_CHG_USR, DOC_CARY, BIZ_FILE_NM, CRT_USR, CRT_DT, EDT_USR, EDT_DT, BIZ_FILE_SAVE_NM, AFF_REG_NOTE, AFF_PRS_NOTE, COST_NOTE, REG_GBN, RLT_NM)
SELECT 'H10' BRCH_ID, 
        30000 + ROWNUM TUB_SEQ, 
        B.ATTR01 TUB_NM, 
        ATTR02 TUB_TEL, 
        ATTR03 TUB_FAX, 
        ATTR04 TUB_ADDR, 
        ATTR05 TUB_ZIP, 
        ATTR06 BAG_AGC_AMT, 
        ATTR07 ETC_AGC_AMT, 
        ATTR08 SIN_NM, 
        ATTR09 SIN_TEL, 
        ATTR10 SIN_GBN, 
        ATTR11 SIN_5, 
        ATTR12 SIN_10, 
        ATTR13 SIN_15, 
        ATTR14 SIN_20, 
        ATTR15 SIN_25, 
        ATTR16 SIN_99, 
        ATTR17 RCP_GBN, 
        ATTR18 BIL_GBN, 
        ATTR19 DEAL_STS, 
        ATTR20 DEAL_STOP_RSN, 
        ATTR21 HNA_CHG_USR, 
        ATTR22 DOC_CARY, 
        NULL BIZ_FILE_NM, 
        'SYSTEM' CRT_USR, 
        SYSDATE CRT_DT, 
        'SYSTEM' EDT_USR, 
        SYSDATE EDT_DT, 
        NULL BIZ_FILE_SAVE_NM, 
        NULL AFF_REG_NOTE, 
        NULL AFF_PRS_NOTE, 
        NULL COST_NOTE, 
        ATTR23 REG_GBN, 
        ATTR24 RLT_NM
  FROM (SELECT ATTR01, MIN(ID) AS M_ID
          FROM ERP_TEMP_TABLE
         GROUP BY ATTR01
       ) A, ERP_TEMP_TABLE B
  WHERE A.M_ID = B.ID       
         

DELETE FROM   TB_CC_TIEUPCHG_LST
  
-- 제휴사 담당 넣기
INSERT INTO TB_CC_TIEUPCHG_LST
(BRCH_ID, TUB_SEQ, CHG_SEQ, CHG_NM, CHG_HP, CHG_TEL, CHG_POS, TEL_OPN_YN, DESC_PRV, DPST_NM, NOTE, CRT_USR, CRT_DT, EDT_USR, EDT_DT)
SELECT 'H10' BRCH_ID,
       B.TUB_SEQ, 
       ROWNUM CHG_SEQ,
       SUBSTR(ATTR08,1,3)  CHG_NM, 
       NULL CHG_HP,
       ATTR09 CHG_TEL,
       SUBSTR(ATTR08,4) CHG_POS, 
       'Y' TEL_OPN_YN, 
       NULL DESC_PRV, 
       NULL DPST_NM, 
       NULL NOTE, 
       'SYSTEM' CRT_USR, 
       SYSDATE CRT_DT, 
       'SYSTEM' EDT_USR, 
       SYSDATE EDT_DT
  FROM ERP_TEMP_TABLE A, TB_CC_TIEUP_LST B
 WHERE A.ATTR01 = B.TUB_NM
  
TB_CC_DEPT_BAS 
 


  
-- 사용자 넣기
INSERT INTO TB_CC_USER_LST
(BRCH_ID, USR_ID, DEPT_CD, USR_NM, USR_GBN, TEL_NO, HP_NO, EMAIL, ST_DT, ED_DT, ADDR, USE_YN, CRT_USR, CRT_DT, EDT_USR, EDT_DT)
SELECT 'H10' BRCH_ID, 
        USR_ID, 
        '110000' DEPT_CD, 
        USR_ID USR_NM, 
        '10' USR_GBN, 
        NULL TEL_NO, 
        NULL HP_NO, 
        NULL EMAIL, 
        '20000101' ST_DT, 
        NULL ED_DT, 
        NULL ADDR, 
        'Y' USE_YN, 
        'SYSTEM' CRT_USR, 
        SYSDATE CRT_DT, 
        'SYSTEM' EDT_USR, 
        SYSDATE EDT_DT
  FROM (SELECT ATTR21 USR_ID
          FROM ERP_TEMP_TABLE  
         WHERE ATTR21 IS NOT NULL
         GROUP BY ATTR21
      )    
           

INSERT INTO TB_CC_LOGIN_LST   
(BRCH_ID, USR_ID, USR_IP, USR_PWD, FAIL_CNT, LOCK_YN, PWD_EDT_DT, PWD_TP, LST_LOGIN_DT, USE_YN, CRT_USR, CRT_DT, EDT_USR, EDT_DT)
SELECT 'H10' BRCH_ID, 
       USR_ID, 
       NULL  USR_IP, 
       '1234' USR_PWD,  
       0 FAIL_CNT, 
       'N' LOCK_YN, 
       SYSDATE PWD_EDT_DT, 
       'N' PWD_TP, 
       NULL LST_LOGIN_DT, 
       'Y' USE_YN, 
        'SYSTEM' CRT_USR, 
        SYSDATE CRT_DT, 
        'SYSTEM' EDT_USR, 
        SYSDATE EDT_DT
  FROM (SELECT ATTR21 USR_ID
          FROM ERP_TEMP_TABLE  
         WHERE ATTR21 IS NOT NULL
         GROUP BY ATTR21
      )    